# Generated by Django 5.2.2 on 2025-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_booking_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
