# Generated by Django 5.2.2 on 2025-06-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('place_id', models.IntegerField()),
                ('date', models.DateField()),
                ('days', models.IntegerField()),
                ('notes', models.IntegerField()),
            ],
        ),
    ]
