# Generated by Django 5.2.2 on 2025-06-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_booking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
