# Generated by Django 5.2.2 on 2025-06-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_destinations_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('subject', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField()),
                ('query_response', models.TextField(blank=True, null=True)),
                ('reponder_id', models.IntegerField(blank=True, null=True)),
                ('responder_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
