# Generated by Django 5.2.2 on 2025-06-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_destinations_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('query_response', models.TextField()),
                ('reponder_id', models.IntegerField()),
                ('responder_name', models.CharField(max_length=100)),
            ],
        ),
    ]
