# Generated by Django 5.2.2 on 2025-06-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
