# Generated by Django 5.2.2 on 2025-06-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
