# Generated by Django 5.2.2 on 2025-06-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_queries_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
