# Generated by Django 5.2.2 on 2025-06-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_queries_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
