# Generated by Django 5.2.2 on 2025-06-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_queries_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='query_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='reponder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
