# Generated by Django 5.2.2 on 2025-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_queries_user_id_queries_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
